name: flutter_qq_ads
description: 【持续更新】FlutterAds 致力于构建优质的 Flutter 广告插件，这是其中一款基于「腾讯广告、广点通、优量汇」的广告插件
version: 2.8.0
homepage: https://github.com/FlutterAds
repository: https://github.com/FlutterAds/flutter_qq_ads
issue_tracker: https://github.com/FlutterAds/flutter_qq_ads/issues
documentation: https://github.com/FlutterAds/flutter_qq_ads/wiki
topics: [flutterads, ads, qq, adnet, income]
funding: [https://github.com/FlutterAds/.github]

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.zero.flutter_qq_ads
        pluginClass: FlutterQqAdsPlugin
      ios:
        pluginClass: FlutterQqAdsPlugin
