name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
    - develop
    - master
  pull_request:
    branches:
      - develop
    
# on: push    # Default will running for every branch.
    
jobs:
  build:
    # This job will run on macos virtual machine
    runs-on: macos-latest
    steps:
    
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '8.x'
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        #channel: 'beta' # 'dev', 'alpha', default to: 'stable'
        flutter-version: '1.22.x' # you can also specify exact version of flutter
    
    # Get flutter dependencies.
    - run: flutter pub get
    
    # Check for any formatting issues in the code.
    - run: flutter format --set-exit-if-changed .
    
    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .
    
    # Run widget tests for our flutter project.
    - run: flutter test
    
    #####
    # Build app
    #####
    #Build ios
    - run: cd example && flutter precache
    - run: cd example/ios && pod install
    - run: cd example && flutter build ios --release --no-codesign -v
    
    # Build apk.
    - run: cd example && flutter build apk -v
    
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: example/build/app/outputs/apk/release/app-release.apk
