name: Gitee Sync

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/FlutterAds
        dst: gitee/FlutterAds
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        account_type: org
        timeout: 600
        force_update: true
        static_list: "flutter_qq_ads"
