name: Publish

on:
#   push:
#     branches:
#     - develop
#     - master
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.PUB_OAUTH_ACCESS_TOKEN }}
          flutter_package: true
          skip_test: false
          dry_run: false
