name: Publish

on:
  push:
    branches:
    - develop
    - master
  release:
    types: [published]

jobs:
  publish:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.PUB_OAUTH_ACCESS_TOKEN }}
          flutter_package: true
          skip_test: false
          dry_run: true
          
      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - uses: subosito/flutter-action@v1
        with:
          #channel: 'beta' # 'dev', 'alpha', default to: 'stable'
          flutter-version: '1.22.x'
      # fix Permission denied
      - run: sudo chown -R $USER $PWD
      - run: cd example && flutter build apk --target-platform android-arm
      - name: Upload to Pgyer
        run: curl -F 'file=@example/build/app/outputs/apk/release/app-release.apk' -F '_api_key=${{ secrets.PGYER_API_KEY }}' https://www.pgyer.com/apiv2/app/upload
